Target only the current session for tmux set commands
vimpostor/vim-tpipeline pull request #43
Opened 2022-12-21 21:47 UTC by davidsierradz

Fixes #42

2022-12-21 23:17 UTC, vimpostor requested changes
Thanks for doing this!

To make the unit test pass, you also need to apply the following diff:
```diff
diff --git a/tests/test_general.vim b/tests/test_general.vim
index d5a2c5c..deedc66 100644
--- a/tests/test_general.vim
+++ b/tests/test_general.vim
@@ -27,7 +27,7 @@ func Read_socket()
 endfunc
 
 func Test_autoembed()
-	call assert_equal('status-left "#(cat #{socket_path}-\\#{session_id}-vimbridge)"', trim(system('tmux show-options -g status-left')))
+	call assert_equal('status-left "#(cat #{socket_path}-\\#{session_id}-vimbridge)"', trim(system('tmux show-options status-left')))
 endfunc
 
 func Test_socket()
```

2022-12-21 23:17 UTC, vimpostor commented on autoload/tpipeline.vim
> +	let s:tmux_server_id = '$' . strcharpart(tmux, strridx(tmux, ",") + 1)
Are you sure that we need the `'$'` for the server id to later also pass to the other commands? If I understand correctly, `tmux set -t` expects the session id without `$`, e.g. `tmux set -t 0`, so I think we would need to store it without the `$`.

2022-12-21 23:17 UTC, vimpostor commented on autoload/tpipeline.vim
> +			let script = 'tmux set -t ' . shellescape(s:tmux_server_id) . ' ' . o . '; ' . script
I am wondering if we even need `-t`. From my testing it looks like not passing any `-t` or `-g` option (just `tmux set`) will default to the current session, can you confirm this?

2022-12-22 12:38 UTC, davidsierradz commented on autoload/tpipeline.vim
> +	let s:tmux_server_id = '$' . strcharpart(tmux, strridx(tmux, ",") + 1)
Because `-t` can be any of target-client, target-session, target-window, or target-pane, the `'$'` make it explicit that we want to target a session id (`'@'` for window and `':'` for pane), I guess tmux is smart enough to understand that the options we are setting are session's options, so it assumes a session id when we don't pass the `'$'`.

2022-12-22 12:43 UTC, davidsierradz commented on autoload/tpipeline.vim
> +			let script = 'tmux set -t ' . shellescape(s:tmux_server_id) . ' ' . o . '; ' . script
You are right, because the `status-...` options are session options, we don't need to pass any explicit target. Will update. Thanks!

2022-12-22 14:50 UTC, vimpostor commented on autoload/tpipeline.vim
> +			let script = 'tmux set -t ' . shellescape(s:tmux_server_id) . ' ' . o . '; ' . script
Indeed: https://github.com/tmux/tmux/blob/70ff8cfe1e06987501a55a32df31d1f69acd2f99/options-table.c#L692


I think the tmux manual is a bit confusing, because it makes it seem like not specifying a flag will always mean a session option:

```
     set-option [-aFgopqsuUw] [-t target-pane] option value
                   (alias: set)
             Set a pane option with -p, a window option with -w, a server option with -s, otherwise a session op‐
             tion.
```

But apparently that is not the case: https://github.com/tmux/tmux/blob/master/cmd-set-option.c#L131

2022-12-22 14:56 UTC, merged

2022-12-22 14:56 UTC, vimpostor commented
Thanks again!