Fix interfering with typing when clearing stl for lualine
vimpostor/vim-tpipeline pull request #54
Opened 2023-05-04 16:43 UTC by defr0std

I've come across a strange issue.

I am using lualine, telescope, and vim-tpipeline. I also enable tpipeline_clearstl since I use a global status line.

I've discovered that updating the statusline may interfere with typing in a window. This often happens for me in telescope. See the screen recording below. When trying to type "nvim he", the cursor jumps back when changing the statusline and you end up typing something else.

https://user-images.githubusercontent.com/16953692/236268068-7b114ab0-086d-440e-be64-b42a9068ba24.mov

I've narrowed this down to updating the statusline, even if we set it to the current value. Perhaps this is some peculiar neovim behavior, but I guess that would take a lot of time to figure this out. In any case, it wouldn't hurt checking the statusline value in this plugin to fix the problem.

2023-05-04 21:51 UTC, vimpostor requested changes

2023-05-04 21:51 UTC, vimpostor commented on autoload/tpipeline/lualine.vim
> +		noa let s = getwinvar(win_getid(i), '&stl')
Why does this need a `noautocmd`? What kind of autocmd do you think could be triggered by a read operation like `getwinvar()`?

2023-05-05 09:31 UTC, defr0std commented on autoload/tpipeline/lualine.vim
> +		noa let s = getwinvar(win_getid(i), '&stl')
To be honest, I have shamelessly copy-pasted this line from here: https://github.com/vimpostor/vim-tpipeline/blob/master/autoload/tpipeline/lualine.vim#L23. I could remove it in both places for constistency.

2023-05-05 18:26 UTC, defr0std commented on autoload/tpipeline/lualine.vim
> +		noa let s = getwinvar(win_getid(i), '&stl')
Sure, done.

2023-05-05 18:56 UTC, vimpostor commented
Thanks!

2023-05-05 18:56 UTC, merged

2023-09-19 21:33 UTC, defr0std commented
Hi @vimpostor,

It seems that this issue has resurfaced in the latest version, although the code in this pr was not touched. Perhaps there is some other code path which triggers such behavior, but I cannot figure out where it happens.

Reverting to the original commit df0267194271714a7ddc2375897778fd24583a47 definitely fixes the problem.

It's not an issue for me, since I can just keep using the plugin at that commit, but just sharing in case somebody else notices this too.

2023-09-19 22:02 UTC, vimpostor commented
Could you maybe bisect this? There have been really only 2 commits that affect production code since then:

- 2c88f0b
- 2889cbd

Alternatively you can provide your config so that I can try to reproduce.